#!/bin/bash

#script utk convert film dari gif ke mp4

clear
echo Convert mulai...

film=*.gif

for f in $film
do 
	
	ffmpeg -i "$f" -c:v libx264 "${f%.gif}.mp4"
	rm "$f"

done

echo Convert selesai
notify-send ".gif to .mp4 fiished"
