#!/bin/bash

#script utk convert format dan encoder film

clear
echo Convert mulai...

film=*.wmv

for f in $film
do 
	
	ffmpeg -i "$f" -c:v libx264 -c:a aac "${f%.wmv}.mp4"
	rm "$f"

done

echo Convert selesai
notify-send "Convert finished"
