#!/bin/bash

#script utk convert format dan encoder film

clear
echo Convert mulai...

film=*.gif

for f in $film
do 
	
	ffmpeg -i "$f" -c:v libx264 -c:a aac "${f%.gif}.mp4"
#	rm "$f"

done

echo Convert selesai
notify-send "Convert finished"
