#!/bin/bash

#script utk ubah ukuran resolusi film

clear
echo Convert mulai...

film=*.mp4

for f in $film
do 
	
	ffmpeg -i "$f" -vf scale=640:480 "${f%.mp4}_e.mp4"
	rm "$f"

done

echo Convert selesai
notify-send "Scaling finished"
