#!/bin/bash

#####download dari mega.nz

clear
echo Mulai unduh
echo
megaget /Root/$1 -u username@email.com -p password &&
notify-send "$1 telah selesai diunduh " &&
telegram-cli -W -e "msg telegram_account $1 sudah selesai diunduh" ||
notify-send "unduhan $1 terputus" ||
