#! /bin/bash

while true;
do
    f=$(cat /sys/class/thermal/thermal_zone0/temp)
    t=$(echo $f | cut -b -2).$(echo $f | cut -b 3-)°C
    d=$(date '+%H:%M')
    root=$(lsblk -lf | awk '/^sda3/ {print $6":"$5}')
    home=$(lsblk -lf | awk '/^sda4/ {print $6":"$5}')
    power=$(cat /sys/class/power_supply/BAT0/capacity)%
    wifi=$(nmcli device wifi list | awk '/^*/ {print $2}')
    xsetroot -name "$wifi|$power|$root|$home|$t|$d"
    sleep 0.1;
done;
